- hosts: localhost
  become: true
  pre_tasks:
    - name: update repositories
      apt: update_cache=yes
      changed_when: False
  tasks:
    - include: tasks/core-setup.yml
    - include: tasks/node-setup.yml
    - include: tasks/zsh-setup.yml
    - include: tasks/chrome.yml
    - include: tasks/productivity-tools.yml
    # - include: tasks/dotfiles.yml
