- name: Install System Packages 1 (build-essential, cmake, pkg-config, pthread)
  apt:
    name: ["build-essential", "cmake", "pkg-config", "libpthread-stubs0-dev"]
  tags:
    - install
    - core
- name: Install System Packages 2 (lua, unzip, libtool, libtool-bin, gettext)
  apt:
    name: [ "lua5.1", "unzip", "libtool", "libtool-bin", "gettext"]
  tags:
    - install
    - core
- name: Install System Packages 3 (the rest)
  apt: name={{item}}
  with_items:
    - fonts-powerline
    - jq
    - fonts-font-awesome
    - curl
    - htop
    - lsof
    - i3
    - feh
    - rofi
    - stow
    - ccache
    - ninja-build
    - python3-pip
    - dconf-editor
    - nvidia-settings
    - pavucontrol
    - moreutils
    - clangd
  tags:
    - install
    - core

