
- name: add PPA for Alacritty
  apt_repository:
    repo: ppa:aslatter/ppa
- name: install packages
  apt: name={{item}}
  with_items:
    - alacritty
    - fzf
    - tmux
    - i3lock
    # install it via .deb package
    #- nvim
    #- flameshot
    - xautolock
    - tldr
